version: '3.3'
services:
    hls-xmltv:
        build: .
        container_name: HLS-XMLTV
        ports:
            - '3000:80'
        environment:
            - "MY_IPS=${MY_IPS}"
        volumes:
            - '/your/concat/list/dir/:/HLS-XMLTV/concat_lists/'
            - '/your/config/dir/:/HLS-XMLTV/config/'
            - '/your/channels/dir/:/HLS-XMLTV/channels/'
            - '/your/cache/dir/:/HLS-XMLTV/cache/'
        tmpfs:
            - '/var/www/html/streams:exec,size=1G,mode=777,uid=82,gid=82'
            - '/tmp:exec,mode=777'

        network_mode: bridge
        
        
        
        
# [docker run command for users without compose]
# docker run -d   -it   --name HLS-XMLTV   -p 3000:80   --env "MY_IPS=$( hostname -I | cut -d ' ' -f 1 ):3000" --mount type=tmpfs,destination=/var/www/html/streams,tmpfs-mode=1770,tmpfs-size=1073741274   -v /usr/local/bin/HLS_XMLTV/concattest/:/HLS-XMLTV/concat_lists/   -v /usr/local/bin/HLS_XMLTV/configtmp/:/HLS-XMLTV/config/   -v /usr/local/bin/HLS_XMLTV/channels/:/HLS-XMLTV/channels/ 40004e090a59
